# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

variables:
  env-process: prod

pipelines:
  default:
    - step:
        script: 
           - npm install
  branches:
    develop: #deploy no ambiente de teste
      - step:
          script:            
            - npm install      
            - npm run build
            - apt-get update && apt-get install -y awscli
            - aws configure set preview.cloudfront true
            - npm run deploy
    master: #deploy no ambiente de producao
      - step:
          script:       
            - npm install -g yarn
            - yarn 
            - yarn run build
            - apt-get update
            - apt-get install -y python-pip
            - pip install --upgrade --user awscli
            - aws configure set preview.cloudfront true
            - npm run deploy