# This is a sample build configuration for Javascript.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

variables:
  env-process: prod

pipelines:
  default:
    - step:
        script: 
           - npm install
  branches:
    develop: #deploy no bucket front.assertiva
      - step:
          script:            
            - npm install -g yarn
            - yarn 
            - yarn run build
            - apt-get update && apt-get install -y python-dev && apt-get install -y python-pip
            - pip install --upgrade awscli
            - aws configure set preview.cloudfront true
            - aws s3 sync public s3://front.assertiva --delete --cache-control 'public, max-age=14400'
            - aws cloudfront create-invalidation  --distribution-id EGO3V7A2E1X5N --paths /*
    master: #deploy no bucket front.assertiva
      - step:
          script:       
            - npm install -g yarn
            - yarn 
            - yarn run build
            - apt-get update && apt-get install -y python-dev && apt-get install -y python-pip
            - pip install --upgrade awscli
            - aws configure set preview.cloudfront true
            - aws s3 sync public s3://app.assertiva --delete --cache-control 'public, max-age=14400'
            - aws cloudfront create-invalidation  --distribution-id E38WNSBQWLMXU5 --paths /*