//https://observer.assertivasolucoes.com.br/monitoraapi

export const URL_CARREGAR_CARTEIRAS = "https://observer.assertivasolucoes.com.br/monitoraapi/carregarcarteiras"
export const URL_ADICIONAR_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/adicionarcarteira"
export const URL_EDITAR_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/editarcarteira"
export const URL_REMOVER_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/removercarteira"
export const URL_CARREGAR_DOCUMENTOS_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/carregardocumentos"
export const URL_EDITAR_DOCUMENTOS_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/editardocumento"
export const URL_ADICIONAR_DOCUMENTO_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/adicionardocumento"
export const URL_REMOVER_DOCUMENTO_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/editarDocumento"
export const URL_ALTERAR_STATUS_DOCUMENTO_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/alterarstatusdocumento"
export const URL_DETALHES_DOCUMENTO_CARTEIRA = "https://observer.assertivasolucoes.com.br/monitoraapi/carregarDocumento"

export const CLOSE_MESSAGE_MONITORA = "CLOSE_MESSAGE_MONITORA"
export const EDITAR_CARTEIRA_MONITORA = "GET_CARTEIRAS_MONITORA"
export const GET_CARTEIRAS_MONITORA = "GET_CARTEIRAS_MONITORA"
export const GET_DOCUMENTOS_MONITORA = "GET_DOCUMENTOS_MONITORA"
export const GET_DOCUMENTOS_DETALHES_MONITORA = "GET_DOCUMENTOS_DETALHES_MONITORA"
export const GET_DOCUMENTOS_CARTEIRA_MONITORA = "GET_DOCUMENTOS_CARTEIRA_MONITORA"
export const VISUALIZAR_DOCUMENTOS_CARTEIRA_MONITORA = "VISUALIZAR_DOCUMENTOS_CARTEIRA_MONITORA"
export const LOADING_MONITORA = "LOADING_MONITORA"
export const NOVA_CARTEIRA_MONITORA = "NOVA_CARTEIRA_MONITORA"
export const NOVO_DOCUMENTO_MONITORA = "NOVO_DOCUMENTO_MONITORA"
export const SHOW_DOCUMENTOS_DETALHES = "SHOW_DOCUMENTOS_DETALHES"