export const URL_CREDITO_SEARCH_CHEQUE = "https://managerprovider.assertivasolucoes.com.br/credito/1006/consultar"
export const URL_CREDITO_SEARCH_COMPLETA = "https://managerprovider.assertivasolucoes.com.br/credito/5017/consultar"
export const URL_CREDITO_SEARCH_COMPLETA_PJ = "https://managerprovider.assertivasolucoes.com.br/credito/5018/consultar"
export const URL_CREDITO_SEARCH_INTERMEDIARIA_PF = "https://managerprovider.assertivasolucoes.com.br/credito/5050/consultar"
export const URL_CREDITO_SEARCH_INTERMEDIARIA_PJ = "https://managerprovider.assertivasolucoes.com.br/credito/5049/consultar"
export const URL_CREDITO_SEARCH_INTERMEDIARIAPLUS_PF = "https://managerprovider.assertivasolucoes.com.br/credito/5052/consultar"
export const URL_CREDITO_SEARCH_INTERMEDIARIAPLUS_PJ = "https://managerprovider.assertivasolucoes.com.br/credito/5051/consultar"
export const URL_CREDITO_SEARCH_SIMPLES = "https://managerprovider.assertivasolucoes.com.br/credito/5070/consultar"
export const URL_CREDITO_LAST_QUERIES = "https://managerprovider.assertivasolucoes.com.br/credito/ultimas-consultas/consultar"

export const SEARCH_BY_LOCALIZE_CNPJ_IN_CREDITO = "SEARCH_BY_LOCALIZE_CNPJ_IN_CREDITO"
export const SEARCH_BY_LOCALIZE_CPF_IN_CREDITO = "SEARCH_BY_LOCALIZE_CPF_IN_CREDITO"
export const SEARCH_BY_LOCALIZE_CPF = "SEARCH_BY_LOCALIZE_CPF"
export const SEE_CREDITO_MODEL = "SEE_CREDITO_MODEL"
export const CLOSE_CREDITO_MODEL = "CLOSE_CREDITO_MODEL"
export const LOADING_CREDITO = "LOADING_CREDITO"
export const CLOSE_MESSAGE_ERROR_CREDITO = "CLOSE_MESSAGE_ERROR_CREDITO"
export const CLOSE_TAB_CREDITO = "CLOSE_TAB_CREDITO"
export const GET_CREDITO_CHEQUE = "GET_CREDITO_CHEQUE"
export const GET_CREDITO_COMPLETA = "GET_CREDITO_COMPLETA"
export const GET_CREDITO_INTERMEDIARIA = "GET_CREDITO_INTERMEDIARIA"
export const GET_CREDITO_INTERMEDIARIAPLUS = "GET_CREDITO_INTERMEDIARIAPLUS"
export const GET_CREDITO_SIMPLES = "GET_CREDITO_SIMPLES"
export const GET_CREDITO_EXPRESS = "GET_CREDITO_EXPRESS"

export const GET_CREDITO_LAST_QUERIES = "GET_CREDITO_LAST_QUERIES"
export const CHANGE_TAB_CREDITO = "CHANGE_TAB_CREDITO"

export const COMPLETA_CODE = "5017"
export const INTERMEDIARIA_CODE = "5050"
export const INTERMEDIARIA_PLUS_CODE = "5052"
export const SIMPLES_CODE = "5070"
export const CHEQUE_CODE = "1006"
export const EXPRESS_CODE = "1007"