export const GET_VEICULOS_LAST_QUERIES = "GET_VEICULOS_LAST_QUERIES";
export const LOADING_VEICULOS = "LOADING_VEICULOS";
export const ICON_VEICULOS = "ICON_VEICULOS";
export const CLOSE_VEICULOS_MODEL = "CLOSE_VEICULOS_MODEL";
export const SEE_VEICULOS_MODEL = "SEE_VEICULOS_MODEL";

export const AGREGADOS_CODE = "1002";
export const BDV_CODE = "1003";
export const DECODIFICADOR_CODE = "1004";
export const LOCALIZACAO_CODE = "1005";
export const PROPRIETARIOS_CODE = "1006";
export const LEILAO_CODE = "1007";
export const SINISTRO_CODE = "1008";