export const CLOSE_MESSAGE_ERROR_BASECERTA = "CLOSE_MESSAGE_ERROR_BASECERTA"
export const GET_TICKETS_BASECERTA = "GET_TICKETS_BASECERTA"
export const UPLOAD_NOVO_ENRIQUECIMENTO = "UPLOAD_NOVO_ENRIQUECIMENTO"