export const GET_CAMPANHAS_SMS = "GET_CAMPANHAS_SMS";
export const GET_CENTRO_CUSTO_SMS = "GET_CENTRO_CUSTO_SMS";
export const GET_RESPOSTAS_SMS = "GET_RESPOSTAS_SMS"
export const SEND_SMS_RAPIDO = "SEND_SMS_RAPIDO";