export const URL_GET_LAYOUTS_BASECERTA = "https://basecerta.assertivasolucoes.com.br/layouts"
export const URL_GET_TICKETS_BASECERTA = "https://basecerta.assertivasolucoes.com.br/fila"
export const URL_UPLOAD_NOVO_ENRIQUECIMENTO = "https://basecerta.assertivasolucoes.com.br/fila"
export const URL_FILTER_BASECERTA = "https://basecerta.assertivasolucoes.com.br/fila/filter"
export const URL_DOWNLOAD_ENTRADA = "https://basecerta.assertivasolucoes.com.br/fila/downloadEntrada/"
export const URL_DOWNLOAD_SAIDA = "https://basecerta.assertivasolucoes.com.br/fila/downloadSaida/"

export const CLOSE_MESSAGE_ERROR_BASECERTA = "CLOSE_MESSAGE_ERROR_BASECERTA"
export const GET_LAYOUTS_BASECERTA = "GET_LAYOUTS_BASECERTA"
export const GET_TICKETS_BASECERTA = "GET_TICKETS_BASECERTA"
export const GET_DOCUMENTO_ENTRADA_BASECERTA = "GET_DOCUMENTO_ENTRADA_BASECERTA"
export const GET_DOCUMENTO_SAIDA_BASECERTA = "GET_DOCUMENTO_SAIDA_BASECERTA"
export const UPLOAD_NOVO_ENRIQUECIMENTO = "UPLOAD_NOVO_ENRIQUECIMENTO"