export const URL_CARREGAR_CARTEIRAS = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/carregarcarteiras"
export const URL_ADICIONAR_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/adicionarcarteira"
export const URL_EDITAR_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/editarcarteira"
export const URL_REMOVER_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/removercarteira"
export const URL_CARREGAR_DOCUMENTOS_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/carregardocumentos"
export const URL_ADICIONAR_DOCUMENTO_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/adicionardocumento"
export const URL_REMOVER_DOCUMENTO_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/removerdocumento"
export const URL_ALTERAR_STATUS_DOCUMENTO_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/alterarstatusdocumento"
export const URL_VISUALIZAR_DOCUMENTO_CARTEIRA = "http://monitoraapi-prod.sa-east-1.elasticbeanstalk.com/monitoraapi/visualizardocumento"

export const EDITAR_CARTEIRA_MONITORA = "GET_CARTEIRAS_MONITORA"
export const GET_CARTEIRAS_MONITORA = "GET_CARTEIRAS_MONITORA"
export const GET_DOCUMENTOS_MONITORA = "GET_DOCUMENTOS_MONITORA"
export const GET_DOCUMENTOS_CARTEIRA_MONITORA = "GET_DOCUMENTOS_CARTEIRA_MONITORA"
export const LOADING_MONITORA = "LOADING_MONITORA"
export const NOVA_CARTEIRA_MONITORA = "NOVA_CARTEIRA_MONITORA"
export const NOVO_DOCUMENTO_MONITORA = "NOVO_DOCUMENTO_MONITORA"