export const SEE_CREDITO_MODEL = "SEE_CREDITO_MODEL";
export const CLOSE_CREDITO_MODEL = "CLOSE_CREDITO_MODEL";
export const LOADING_CREDITO = "LOADING_CREDITO";
export const CLOSE_TAB_CREDITO = "CLOSE_TAB_CREDITO";
export const GET_CREDITO_LAST_QUERIES = "GET_CREDITO_LAST_QUERIES";
export const CHANGE_TAB_CREDITO = "CHANGE_TAB_CREDITO";