export const LOADING_CADASTRO = "LOADING_CADASTRO";

export const GET_GROUPS_CADASTRO = "GET_GROUPS_CADASTRO";
export const GET_USERS_CADASTRO = "GET_USERS_CADASTRO";
export const GET_CONSULTAS_GRUPO = "GET_CONSULTAS_GRUPO";
export const GET_PERMISSOES_USER = "GET_PERMISSOES_USER";
